kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: opdr4-bc2
  namespace: janjansenn2-dev
  uid: 418da23e-24f6-4980-a718-d1bff003f6cf
  resourceVersion: '998166957'
  generation: 8
  creationTimestamp: '2023-11-22T09:00:25Z'
  managedFields:
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2023-11-22T09:08:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:lastVersion': {}
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2023-11-22T12:50:08Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:output':
            'f:to': {}
          'f:runPolicy': {}
          'f:source':
            'f:git':
              .: {}
              'f:ref': {}
              'f:uri': {}
            'f:secrets': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:dockerfilePath': {}
              'f:pullSecret': {}
            'f:type': {}
          'f:triggers': {}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'opdr4_is:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      pullSecret:
        name: opdr4-secret2
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/xtenone/example-java-app.git'
      ref: main
    secrets:
      - secret:
          name: opdr4-secret
  triggers:
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 2
