apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: java-tag-image
  namespace: ma-van-bijleveld-dev
spec:
  steps:
    - computeResources: {}
      image: 'quay.io/openshift/origin-cli:latest'
      name: java-trigger-buildconfig
      script: |
        #!/usr/bin/env bash
        set -e
        oc tag java:latest java:prd -n ma-van-bijleveld-dev
